# Generated by Django 5.2.5 on 2025-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Category with this title is already exist'}, max_length=40, unique=True)),
                ('image_name', models.CharField(error_messages={'unique': 'Category with this title is already exist'}, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/categories')),
            ],
            options={
                'db_table': 'shop-categories',
            },
        ),
        migrations.CreateModel(
            name='DesktopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=40, unique=True)),
                ('image_name', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/DesktopBanners')),
            ],
            options={
                'db_table': 'shop-desktop-banners',
            },
        ),
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=40, unique=True)),
                ('image_name', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/DesktopBanners')),
            ],
            options={
                'db_table': 'shop-mobile-banners',
            },
        ),
    ]
