# Generated by Django 5.2.6 on 2025-09-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Category with this title is already exist'}, max_length=40, unique=True)),
                ('image_name', models.CharField(error_messages={'unique': 'Category with this title is already exist'}, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/categories')),
            ],
            options={
                'db_table': 'shop-categories',
            },
        ),
        migrations.CreateModel(
            name='DesktopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=40, unique=True)),
                ('image_name', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/DesktopBanners')),
            ],
            options={
                'db_table': 'shop-desktop-banners',
            },
        ),
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=40, unique=True)),
                ('image_name', models.CharField(error_messages={'unique': 'Desktop Banner with this title is already exist'}, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/DesktopBanners')),
            ],
            options={
                'db_table': 'shop-mobile-banners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Product with this title is already exist'}, max_length=60, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
